### ISSUE TITLE
Implement storage container for images

### ISSUE THREAD

**Issue by markdturner** [ATNU/sarum-hymnal#4]

**Comment by jamescummings** [comment]
I assume such a container will be compatible with IIIF?

**Comment by sdowsland** [comment]
Hi @jamescummings Will be using [Cantaloupe](https://medusa-project.github.io/cantaloupe) - Compatible with IIIF 2.0 - to serve the images. Images will be stored in minio which is an AWS S3 compatible object store. See [wiki](https://github.com/ATNU/sarum-hymnal/wiki) for some more details (Wiki is work in progress)

**Comment by sdowsland** [comment]
Completed with commit bd4f75b06bc597ac1d0199b4d58cdadca7a47c5e
